# Generated by Django 5.2.5 on 2025-10-10 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0012_auto_20251006_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("alipay_qr", "支付宝扫码支付"),
                            ("wechat_pay", "微信支付"),
                            ("bank_transfer", "银行转账"),
                        ],
                        default="alipay_qr",
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "alipay_trade_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="支付宝交易号",
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="商户订单号"
                    ),
                ),
                (
                    "qr_code",
                    models.TextField(blank=True, null=True, verbose_name="二维码内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付完成时间"
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="event.eventregistration",
                        verbose_name="活动报名",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付订单",
                "verbose_name_plural": "支付订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "退款中"),
                            ("success", "退款成功"),
                            ("failed", "退款失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "alipay_refund_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="支付宝退款交易号",
                    ),
                ),
                (
                    "out_refund_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="商户退款单号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款完成时间"
                    ),
                ),
                (
                    "refund_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_record",
                        to="event.refundrequest",
                        verbose_name="退款申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款记录",
                "verbose_name_plural": "退款记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
