# Generated by Django 5.2.5 on 2025-10-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("alipay_qr", "支付宝订单码支付"),
                    ("wechat_pay", "微信支付"),
                    ("bank_transfer", "银行转账"),
                ],
                default="alipay_qr",
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
    ]
