# Generated by Django 5.2.5 on 2025-10-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0002_alter_payment_payment_method"),
    ]

    operations = [
        # 这是一个空的迁移文件，用于解决数据库状态不一致的问题
        # 原错误信息显示尝试删除不存在的'description'列
        # 通过添加这个空迁移，我们可以同步Django的迁移状态
    ]