# Generated by Django 5.2.5 on 2025-10-13 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0003_auto_20251013_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="out_trade_no",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=100,
                unique=True,
                verbose_name="商户订单号",
            ),
        ),
    ]
