# Generated by Django 5.2.5 on 2025-10-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0004_alter_payment_out_trade_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="trade_no",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="交易号",
            ),
        ),
    ]