# Generated by Django 5.2.5 on 2025-10-22 13:17

from django.db import migrations, models


def safe_remove_alipay_trade_no(apps, schema_editor):
    # 安全地删除alipay_trade_no字段（如果存在）
    try:
        schema_editor.execute("ALTER TABLE pay_payment DROP COLUMN alipay_trade_no;")
    except Exception:
        # 如果字段不存在或删除失败，忽略错误
        pass


def reverse_safe_remove_alipay_trade_no(apps, schema_editor):
    # 逆向操作，这里可以留空
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0005_auto_20251020_0141"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_alipay_trade_no,
            reverse_code=reverse_safe_remove_alipay_trade_no
        ),
        migrations.RemoveField(
            model_name="payment",
            name="qr_code",
        ),
        migrations.AddField(
            model_name="payment",
            name="buyer",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="支付者账号"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="商品名称"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="out_trade_no",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="商户订单号"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("alipay", "支付宝"),
                    ("wxpay", "微信支付"),
                    ("qqpay", "QQ钱包"),
                    ("tenpay", "财付通"),
                ],
                default="wxpay",
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
    ]