# Generated by Django 5.2.5 on 2025-10-22 13:19

from django.db import migrations


def safe_remove_alipay_trade_no(apps, schema_editor):
    # 安全地删除alipay_trade_no字段（如果存在）
    try:
        schema_editor.execute("ALTER TABLE pay_payment DROP COLUMN alipay_trade_no;")
    except Exception:
        # 如果字段不存在或删除失败，忽略错误
        pass


def reverse_safe_remove_alipay_trade_no(apps, schema_editor):
    # 逆向操作，这里可以留空
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0006_remove_payment_alipay_trade_no_and_more"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_alipay_trade_no,
            reverse_code=reverse_safe_remove_alipay_trade_no
        ),
    ]