# Generated by Django 5.2.5 on 2025-10-22 13:26

from django.db import migrations


def safe_remove_buyer(apps, schema_editor):
    # 安全地删除buyer字段（如果存在）
    try:
        schema_editor.execute("ALTER TABLE pay_payment DROP COLUMN buyer;")
    except Exception:
        # 如果字段不存在或删除失败，忽略错误
        pass


def reverse_safe_remove_buyer(apps, schema_editor):
    # 逆向操作，这里可以留空
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0007_remove_payment_alipay_trade_no"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_buyer,
            reverse_code=reverse_safe_remove_buyer
        ),
    ]