# Generated by Django 5.2.5 on 2025-10-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0008_remove_payment_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="alipay_trade_no",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="buyer",
        ),
    ]
