# Generated by Django 5.2.5 on 2025-09-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawledphoto",
            name="album",
        ),
        migrations.AlterUniqueTogether(
            name="crawledphoto",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="crawledphoto",
            name="user",
        ),
        migrations.RemoveField(
            model_name="crawleduser",
            name="avatar_local_path",
        ),
        migrations.RemoveField(
            model_name="crawleduser",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="crawleduser",
            name="profile_url",
        ),
        migrations.AlterField(
            model_name="crawleduser",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="crawleduser",
            name="username",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="CrawledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("image_urls", models.JSONField(default=list)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("douyin", "抖音"),
                            ("xiaohongshu", "小红书"),
                            ("bilibili", "B站"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform_post_id", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField()),
                ("crawled_at", models.DateTimeField(auto_now_add=True)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="crawler.crawleduser",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取内容",
                "verbose_name_plural": "爬取内容",
                "unique_together": {("platform", "platform_post_id")},
            },
        ),
        migrations.CreateModel(
            name="CrawledMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "图片"), ("video", "视频")], max_length=10
                    ),
                ),
                ("url", models.URLField()),
                ("local_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("douyin", "抖音"),
                            ("xiaohongshu", "小红书"),
                            ("bilibili", "B站"),
                        ],
                        max_length=20,
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_downloaded", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="crawler.crawledpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取媒体",
                "verbose_name_plural": "爬取媒体",
            },
        ),
        migrations.DeleteModel(
            name="CrawledAlbum",
        ),
        migrations.DeleteModel(
            name="CrawledPhoto",
        ),
    ]
