# Generated by Django 5.2.5 on 2025-09-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="display_image",
        ),
    ]
