# Generated by Django 5.2.5 on 2025-09-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crawler_albums",
                to="crawler.crawleruser",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crawler_photos",
                to="crawler.crawleruser",
            ),
        ),
    ]
