# Generated by Django 5.2.5 on 2025-09-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_remove_crawledphoto_album_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawledpost",
            name="comment_count",
        ),
        migrations.RemoveField(
            model_name="crawledpost",
            name="like_count",
        ),
        migrations.RemoveField(
            model_name="crawledpost",
            name="share_count",
        ),
    ]
