# Generated by Django 5.2.5 on 2025-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_remove_photo_display_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
