# Generated by Django 5.2.5 on 2025-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_alter_album_uploaded_by_alter_photo_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawleruser",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$AIgaFC17pg0j3dM65xrI0w$gcbS6m0S0I2F8wQ8S14GFgEz2nIQTM0gD5nVjE5V9uM=",
                max_length=128,
            ),
        ),
    ]
