# Generated by Django 5.2.5 on 2025-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0003_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawleruser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
