# Generated by Django 5.2 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_album_photo_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="display_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/display/"),
        ),
    ]
