# Generated by Django 5.2 on 2025-08-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0009_notification_privatemessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatemessage",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="privatemessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="PrivateMessage",
        ),
    ]
