# Generated by Django 5.2 on 2025-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_privatemessage'),
    ]

    operations = [
    ]