# Generated by Django 5.2 on 2025-09-01 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0013_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "other_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_by_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_conversation_records",
                        to="photos.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "other_user")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pinned_conversations",
            field=models.ManyToManyField(
                related_name="pinned_in_profiles",
                through="photos.PinnedConversation",
                through_fields=("user_profile", "other_user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
