# Generated by Django 5.2 on 2025-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0014_pinnedconversation_userprofile_pinned_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('message', 'Message'), ('mention', 'Mention'), ('favorite', 'Favorite')], max_length=20),
        ),
    ]