# Generated by Django 5.2 on 2025-09-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0015_add_favorite_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("message", "Message"),
                    ("mention", "Mention"),
                    ("favorite", "Favorite"),
                    ("comment_like", "Comment Like"),
                ],
                max_length=20,
            ),
        ),
    ]
