# Generated by Django 5.2.5 on 2025-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_add_reply_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]