# Generated by Django 5.2.5 on 2025-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0018_photo_external_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
