# Generated by Django 5.2.5 on 2025-09-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0019_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_external_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
