# Generated by Django 5.2.5 on 2025-09-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0020_remove_photo_description_remove_photo_title_and_more"),
    ]

    operations = [
        # 已经在 0020 迁移中删除了 description 和 title 字段
        # 此迁移保留为空操作，防止重复删除引发错误
    ]
