# Generated by Django 5.2.5 on 2025-09-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0020_remove_photo_description_remove_photo_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
    ]
