# Generated by Django 5.2.5 on 2025-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0021_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
