# Generated by Django 5.2.5 on 2025-10-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0022_alter_album_approved"),
    ]

    operations = [
        # 字段已在 earlier migrations 中删除，此处保留为空操作以避免重复删除错误
    ]
