# Generated by Django 5.2.5 on 2025-10-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0022_alter_album_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
    ]
