# Generated by Django 5.2.5 on 2025-10-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0023_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        # 由于字段已被删除，此迁移文件改为noop（空操作）
        # migrations.RemoveField(
        #     model_name="photo",
        #     name="description",
        # ),
        # migrations.RemoveField(
        #     model_name="photo",
        #     name="title",
        # ),
    ]