# Generated by Django 5.2.5 on 2025-10-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0024_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        # 字段已在 earlier migrations 中删除，此处保留为空操作以避免重复删除错误
        # migrations.RemoveField(
        #     model_name="photo",
        #     name="description",
        # ),
        # migrations.RemoveField(
        #     model_name="photo",
        #     name="title",
        # ),
    ]