# Generated by Django 5.2.5 on 2025-10-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0024_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
    ]
