# Generated by Django 5.2.5 on 2025-10-22 13:17

from django.db import migrations


def safe_remove_photo_description_title(apps, schema_editor):
    # 安全地删除photo表的description和title字段（如果存在）
    try:
        schema_editor.execute("ALTER TABLE photos_photo DROP COLUMN description;")
    except Exception:
        # 如果字段不存在或删除失败，忽略错误
        pass
        
    try:
        schema_editor.execute("ALTER TABLE photos_photo DROP COLUMN title;")
    except Exception:
        # 如果字段不存在或删除失败，忽略错误
        pass


def reverse_safe_remove_photo_description_title(apps, schema_editor):
    # 逆向操作，这里可以留空
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0025_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_photo_description_title,
            reverse_code=reverse_safe_remove_photo_description_title
        ),
    ]
