# Generated by Django 5.2.5 on 2025-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0026_remove_photo_description_remove_photo_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_create_event",
            field=models.BooleanField(default=False, verbose_name="能否发布活动"),
        ),
    ]
