# Generated by Django 5.2 on 2025-09-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                ("description", models.TextField(verbose_name="活动描述")),
                ("event_time", models.DateTimeField(verbose_name="活动时间")),
                ("location", models.CharField(max_length=200, verbose_name="活动场地")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="是否审核通过"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "摄影活动",
                "verbose_name_plural": "摄影活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模特姓名")),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="模特费用"
                    ),
                ),
                (
                    "outfit_images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_outfits/",
                        verbose_name="模特服装图片",
                    ),
                ),
                (
                    "scene_images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_scenes/",
                        verbose_name="拍摄场景图片",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动模特",
                "verbose_name_plural": "活动模特",
            },
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="场次标题")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="event.eventmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动场次",
                "verbose_name_plural": "活动场次",
                "ordering": ["start_time"],
            },
        ),
    ]
