# Generated by Django 5.2 on 2025-09-09 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                ("description", models.TextField(verbose_name="活动描述")),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="活动模特"),
                ),
                ("event_time", models.DateTimeField(verbose_name="活动时间")),
                ("location", models.CharField(max_length=200, verbose_name="活动场地")),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="活动费用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="是否审核通过"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "摄影活动",
                "verbose_name_plural": "摄影活动",
                "ordering": ["-created_at"],
            },
        ),
    ]
