# Generated by Django 5.2 on 2025-09-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="model_images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_models/",
                verbose_name="模特照片",
            ),
        ),
    ]
