# Generated by Django 5.2 on 2025-09-12 16:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_eventmodel_model_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="活动描述"),
        ),
    ]
