# Generated by Django 5.2 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_poi",
            field=models.TextField(
                blank=True, null=True, verbose_name="活动场地POI信息"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="活动描述"),
        ),
    ]
