# Generated by Django 5.2 on 2025-09-13 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_event_location_poi_alter_event_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_location",
                to=settings.AUTH_USER_MODEL,
                verbose_name="场地提供者",
            ),
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="model_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_model",
                to=settings.AUTH_USER_MODEL,
                verbose_name="模特用户",
            ),
        ),
    ]
