# Generated by Django 5.2 on 2025-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_event_location_user_eventmodel_model_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="vip_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="VIP模特费用",
            ),
        ),
    ]
