# Generated by Django 5.2 on 2025-09-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_eventmodel_vip_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="photographer_count",
            field=models.PositiveIntegerField(default=1, verbose_name="可报名人数"),
        ),
    ]
