# Generated by Django 5.2 on 2025-09-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_eventsession_photographer_count_eventregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmodel",
            name="photographer_count",
        ),
    ]
