# Generated by Django 5.2.5 on 2025-10-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_refundrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="is_refunded",
            field=models.BooleanField(default=False, verbose_name="是否已退款"),
        ),
    ]
