# Generated by Django 5.2.5 on 2025-10-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_eventregistration_is_refunded"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
    ]