# Generated by Django 5.2.5 on 2025-10-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0012_auto_20251006_0036"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="是否已支付"),
        ),
    ]
