# Generated by Django 5.2.5 on 2025-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0013_eventregistration_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待开始"),
                    ("ongoing", "进行中"),
                    ("finished", "已结束"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="活动状态",
            ),
        ),
    ]
